README.markdown

Using the "p" command will not allow colored output in ruby 2.1.2p95 (possibly other versions as well). I spent roughly 30 minutes googling around before I tried using the "puts" command in stead, which worked.

Changing documentation for better output support

---

lib/rainbow.rb

Beginning with version 2, Ruby include native ANSI color support on Windows.
win32console gem fails to load on Windows when Ruby version >= 2. This causes rainbow to disable itself.

use native ANSI color support on Ruby versions >= 2

---

lib/rainbow/color.rb

I was looking through the code and noticed and `else` that appears to have been intended to be an `elsif`. Both cases will raise an `ArgumentError`, but now the error message will contain all valid color names.

Handle invalid color names

---

README.markdown
ext/mkrf_conf.rb
lib/rainbow.rb

This is only required for Ruby < 2.0. Also recognize Cygwin as Windows.
Closes #19 for good :-)

mkrf_conf: Improve the check to install win32console

---

lib/rainbow/presenter.rb
spec/unit/presenter_spec.rb

Since some other methods like color got aliases like foreground color I thought it would be great to have an alias for **bright** called **bold** since for me the term **bold** was much more clear than the term **bright** and I'm sure that I am not the only one.

Added bold alias for bright method

---

.travis.yml
lib/rainbow/null_presenter.rb
spec/support/presenter_shared_examples.rb

NullPresenter should have handled X11 color name.
But, previous implementation lacked this.
I implemented NullPresenter X11 color name methods.
Also added a X11 color name to shortcut name shared example.

FIX #34: NullPresenter handles X11 color name

---

lib/rainbow/color.rb

Ruby 2.4 unifies Fixnum and Bignum into Integer: https://bugs.ruby-lang.org/issues/12005
Fix the following waning.
```
% ruby -v
ruby 2.4.0dev (2016-09-26 trunk 56247) [x86_64-darwin13]
% rake spec
(snip)
/Users/koic/src/github.com/sickill/rainbow/lib/rainbow/color.rb:15:
warning: constant ::Fixnum is deprecated
```
Thanks.

Fix a warning in ruby 2.4.0dev

---

.travis.yml
Gemfile

This PR changes the Travis build matrix a little, so that it's possible to add build-specific ENV vars and settings.
- It adds Bundler's folder to cache
- It uses the default `bundle exec rake` for a build task
- The versions come ruby-install of today
- added --debug to JRuby to improve accuracy of code coverage calculation
This indicates that 2.4.0 **already** builds and runs tests **without any output like this**:
```
rainbow-2.1.0/lib/rainbow/color.rb:15: warning: constant ::Fixnum is deprecated
```

Travis: include 2.4.0 and use exact versions

---

Rakefile

See #40
This PR changes the Rakefile to make Bundler and RSpec optional. When no RSpec is available, the `spec` task is defined a "no-op" with no output.
Here's an example, mentioning the role of Makefile/Rakefile re: "ext": https://en.wikibooks.org/wiki/Ruby_Programming/RubyGems#How_to_use_a_Rakefile_instead_of_a_Makefile Thanks to everyone in #40 for being helpful and sharing their findings.
Does this help you folks with the issue?

Rakefile: Bundler, RSpec optional

---

ext/mkrf_conf.rb

This PR adds a blank Rakefile to the ext folder when building, so that rake hits that instead of the main Rakefile.
See #42, #40.

Ext: add a blank rakefile when it works

---

lib/rainbow/color.rb

Follow-up of 2dba7b2f42768ea80a19435a504939072ed935e3
Pre-2.4.0: Integer == Fixnum => false
2.4.0: Integer == Fixnum => true
@koic @sickill

Fix `Color.build` ignoring Integers in older Ruby versions

---

README.markdown
lib/rainbow/ext/string.rb
lib/rainbow/null_presenter.rb
lib/rainbow/presenter.rb
spec/integration/rainbow_spec.rb
spec/integration/string_spec.rb
spec/unit/null_presenter_spec.rb
spec/unit/presenter_spec.rb

I confirmed faint/dark can be used in Terminal.app and iTerm 2 (3.0) in OS X Sierra.
This PR enables to use it..!
Also, fixed bug that calling `bold` when rainbow is not enabled causes no method error.

Add faint/dark method and fix missing bold alias in NullPresenter

---

rainbow.gemspec

In order to address [#57] I have added an open-ended Rake dependency to this gem. Currently when building in environments such as Ubuntu or Alpine linux with applications such as Sinatra (that do not require rake) any gem including Rainbow will cause bundler to fail.
We may want to look at what version of Rake you *really* require. But in the meantime, a dependency on Rake should be added to the gemspec ASAP

Add open-ended rake dependency

---

.travis.yml

This PR updates the CI matrix to use latest JRuby.

Travis: use jruby-9.1.10.0 in CI matrix

---

.travis.yml

This PR only updates the CI matrix to the latest generally available Ruby versions.

Travis: upgrade rubies

---

Changelog.md

I've never seen a Changelog that wasn't in reverse chronological order so it kind of threw me when I looked. Figured I'd update it to meet the more common ordering. Also made all of the headings the same size.

Reverse Changelog order

---

lib/rainbow/global.rb
lib/rainbow/string_utils.rb
spec/integration/uncolor_spec.rb
spec/unit/string_utils_spec.rb

Similar method exists in Perl's Term:ANSIColor as uncolor().
It is useful when:
- test code calls method which can return text with color.
- calling terminal commands which can return text with color.

Add uncolor method

---

.travis.yml
appveyor.yml

This tiny change fixes ~three~ five things:
- speed: RVM does `gem update --system` on its own
- readability: configure `JRUBY_OPTS` as env global
- clarity: Travis YAML config `cache` shorthand for `bundler` corrected
- update: use latest JRuby in CI matrix - `jruby-9.1.14.0` 
- Build fix: used https://www.appveyor.com/docs/lang/ruby/ as a template and harmonized our configuration to that, and the tests began passing.

Travis: RVM note, extract env, cache bundler right; Appveyor: fix build

---

spec/integration/instance_spec.rb
spec/integration/rainbow_spec.rb
spec/integration/string_spec.rb
spec/integration/uncolor_spec.rb
spec/spec_helper.rb
spec/support/presenter_shared_examples.rb
spec/unit/color_spec.rb
spec/unit/namespace_spec.rb
spec/unit/null_presenter_spec.rb
spec/unit/presenter_spec.rb
spec/unit/string_utils_spec.rb
spec/unit/wrapper_spec.rb

This PR configures RSpec to use its [**zero-monkey-patching mode**](https://relishapp.com/rspec/rspec-core/v/3-7/docs/configuration/zero-monkey-patching-mode).
The code changes are to use `RSpec.describe` and `RSpec.shared_examples_for`.

RSpec: disable monkey patching

---

lib/rainbow/color.rb
spec/unit/color_spec.rb

This PR adds a format check when the user inputs a string, addressing the issue #82.
Please note that I'm still not sure enforcing an `ArgumentError` is the best solution because some people could be using a non valid hexadecimal string in their project without any visible impact (i.e `'green'`) and that change could potentially break their code.

Add hexadecimal RGB triplet string format check

---

lib/rainbow/string_utils.rb

I am currently looking into optimizing rainbow colorization a bit. For any large numbers of elements, which need to be colored the time spend in parsing colors and wrapping the strings in escape sequences is significant according to my profiling.
This is just a small change which already is a small improvement in the right direction without needing to change the API.
On my machine, using benchmark.bmbm for 100,000 iterations:
```
Rehearsal -----------------------------------------
orig    0.494690   0.000626   0.495316 (  0.496591)
new     0.392162   0.000046   0.392208 (  0.393326)
-------------------------------- total: 1.253264sec
user     system      total        real
orig    0.509721   0.000010   0.509731 (  0.510783)
new     0.362617   0.000005   0.362622 (  0.363267)
```

Simplify `wrap_with_sgr` method

---

lib/rainbow/ext/string.rb
lib/rainbow/null_presenter.rb
lib/rainbow/presenter.rb
spec/integration/rainbow_spec.rb
spec/integration/string_spec.rb
spec/unit/null_presenter_spec.rb
spec/unit/presenter_spec.rb
spec/unit/string_utils_spec.rb

This PR adds `#cross_out` and its alias `#strike` for both presenters and Strings.

introducing #cross_out

---

.travis.yml
Gemfile
rainbow.gemspec

This PR adds more Rubies to the build matrix and allows use of Bundler 1 or 2.

CI: Allow Bundler 2, add Rubies to CI matrix

---

.rubocop.yml
.travis.yml
Gemfile
Guardfile
Rakefile
appveyor.yml
lib/rainbow.rb
lib/rainbow/color.rb
lib/rainbow/ext/string.rb
lib/rainbow/global.rb
lib/rainbow/null_presenter.rb
lib/rainbow/presenter.rb
lib/rainbow/refinement.rb
lib/rainbow/string_utils.rb
lib/rainbow/version.rb
lib/rainbow/wrapper.rb
lib/rainbow/x11_color_names.rb
rainbow.gemspec
spec/unit/null_presenter_spec.rb

This PR updates the Gemfile use any (aka latest release of) RuboCop.
- Gemspec: _Update_ the lowest-allowed Ruby to ~2.2+~ **2.3**
- RuboCop config: Explicitly set the chosen Ruby requirement
- CI: Drop Ruby 2.1, 2.2 - See #90 
- CI: Add JRuby 9.2.6.0 (latest GA release)
Then **lint** to the new rules.

Use rubocop latest, drop support for Ruby 2.1, 2.2

---

.travis.yml

This PR only updates the CI matrix to the latest generally available Ruby versions.
Source for version numbers: https://github.com/rvm/rvm/blob/master/config/known

CI: Use 2.4.6, 2.5.5, 2.6.3, jruby-9.2.7.0

---

.travis.yml

Simplify to two-part version numbers, use JDK which new and old enough to work with JRuby on Travis.
The part of the installation which got Java onto the machine worked well, now. Fixes #98

CI: Update matrix to use two-part version numbers; use openjdk8, oraclejdk9 to install JRuby

---

.travis.yml

This PR updates the CI matrix to use latest JRuby, **9.2.11.0**.
[JRuby 9.2.11.0 release blog post](https://www.jruby.org/2020/03/02/jruby-9-2-11-0.html)

CI: Use JRuby 9.2.11.0

---

.rubocop.yml

This PR deals with this RuboCop output: **enabling these new cops**.
```
Running RuboCop...
The following cops were added to RuboCop, but are not configured. Please set Enabled to either `true` or `false` in your `.rubocop.yml` file:
- Style/HashEachMethods (0.80)
- Style/HashTransformKeys (0.80)
- Style/HashTransformValues (0.80)
For more information: https://docs.rubocop.org/en/latest/versioning/
Inspecting 15 files
...............
```

(chore) Add v0.80 RuboCop cops

---

.rubocop.yml
Gemfile

In order to get a green build, this PR pins the RuboCop version to the last supported version which runs on Ruby 2.3.

chore: Pin RuboCop to old version, which supports Ruby 2.3

---

README.markdown

This is a minor README update to show a screenshot of the code example, without having to look at the linked video:
Hope you find this useful.
Thanks for maintaining rainbow!

Add screenshot of example in README

---

rainbow.gemspec

This repairs the gemspec files directive.
Fixes #113

fix: Include all lib/ files

---

.rubocop.yml
.travis.yml
appveyor.yml
rainbow.gemspec

In order to pass tests on Windows CI, drop the Ruby 2.3 target, which is not capable of connecting to https to get gems from RubyGems.org.
This updates the CI config and the linting configuration.

Require Ruby 2.4

---

README.markdown

This PR adds the CI status badge.

docs: Add CI status badge

---

lib/rainbow/string_utils.rb

When there are lots of offenses, rubocop spends ~2.5% of the time in the `wrap_with_sgr` method. 
100% of the strings in rubocop are wrapped only once (no chaining).
This PR optimizes that method from 2x (for shorter strings) to 1.5x (for longer). For strings already having control sequences performance is the same.
```ruby
require "bundler/inline"
gemfile(true) do
source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }
gem "benchmark-ips"
gem "rainbow", github: "sickill/rainbow"
end
module Rainbow
class StringUtils
def self.optimized_wrap_with_sgr(string, codes)
return string if codes.empty?
seq = "\e[" + codes.join(";") + "m"
if string.include?("\e")
string = string.sub(/^(\e\[([\d;]+)m)+/) { |m| m + seq }
string += "\e[0m" unless string.end_with? …
```

Optimize wrapping with SGR

---

lib/rainbow/presenter.rb
spec/integration/refinement_spec.rb

See issue #128. I used define_method for all the named color methods instead of method_missing, and added a spec for the issue.

Allow X11 color methods using refinement interface 

---

README.markdown

I was looking for a way to determine the visual length of previously rainbow-ized strings. After some searching I came across exactly what I needed: https://github.com/ku1ik/rainbow/pull/54
I hope adding this section to the readme will make the method easier for others to find 😊

[README] Document `Rainbow.uncolor` method

---

Gemfile

Try to get to green on Ruby 3.4.

Gemfile: add required supporting base64 gem, fiddle gem

---

.github/workflows/ci.yml
Changelog.md

Ensure that this library works on Ruby 3.3 and 3.4 in CI.

Support Ruby 3.3 and 3.4 in CI

---

README.markdown

This PR drops a badge for a defunct service.

README.markdown: Remove CodeClimate badge
